trigger:
- main  # Trigger pipeline on commits to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image to use

steps:
- script: |
    python -V  # Verify Python version
    pip install -r requirements.txt  # Install dependencies
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover -s tests  # Run your tests here (if applicable)
  displayName: 'Run tests'

- script: |
    python app.py  # Start Flask server
  displayName: 'Run Flask application'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'flask-app'
  displayName: 'Publish Flask application artifact'
