trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -V
    pip install flask  # Install Flask if not already installed
  displayName: 'Install dependencies'

- script: |
    python app.py &  # Start Flask application in the background
    sleep 5  # Give time for Flask to start (adjust as needed)
  displayName: 'Run Flask application'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'flask-app'
  displayName: 'Publish Flask application artifact'
