trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use Python 3.x version

- script: |
    python -m pip install --upgrade pip
    pip install Flask
  displayName: 'Install dependencies'

- script: |
    python app.py & echo $! > flask_app.pid
    sleep 10  # Allow some time for the Flask app to start
    curl http://127.0.0.1:5000  # Test accessing the Flask app
  displayName: 'Run Flask application'

- script: |
    kill $(cat flask_app.pid)
    rm flask_app.pid
  displayName: 'Stop Flask application'
